server:
  port: 9090

#logbook style: https://github.com/zalando/logbook#configuration
logbook:
  format:
    style: splunk

logging:
  file:
    path: logs
    name: logs/admin-service.log
  level:
    #set for logbook write into log
    org.zalando.logbook: TRACE